#!/usr/bin/env bash
shopt -s globstar
set -e

ROOT="$(git rev-parse --show-toplevel)"

pushd $ROOT/api
npx eslint src
popd

pushd $ROOT/lom
npx eslint src
popd

# Formatting step
$ROOT/api/node_modules/.bin/prettier --ignore-unknown --write $ROOT/{api,lom}/{eslint.config.js,src/**/*.ts}
git update-index --again
exit 0